version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - mongo
    env_file:
      - packages/server/.env
    environment:
      - TYPEORM_PORT=5432
      - TYPEORM_HOST=postgres


  postgres:
    image: postgres:17
    container_name: cvai_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cvai
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: cvai_mongo
    environment:
      - MONGO_INITDB_DATABASE=cvai
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# TODO: add ptp service. Fetch it from docker-hub

volumes:
  postgres_data:
  mongo_data:
