option_settings:
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: production
  aws:elasticbeanstalk:container:nodejs:
    NodeVersion: 20.x
  aws:autoscaling:launchconfiguration:
    InstanceType: t2.micro
    EC2KeyName: YOUR_EC2_KEY_NAME
  aws:elasticbeanstalk:environment:
    ServiceRole: aws-elasticbeanstalk-service-role