Resources:
  AWSEBRDSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t3.micro
      DBName: cvai
      Engine: postgres
      EngineVersion: '15.5'
      MasterUsername: !Ref TYPEORM_USERNAME
      MasterUserPassword: !Ref TYPEORM_PASSWORD
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !GetAtt InstanceSecurityGroup.GroupId

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances

option_settings:
  aws:elasticbeanstalk:application:environment:
    TYPEORM_HOST: !GetAtt AWSEBRDSDatabase.Endpoint.Address
    TYPEORM_PORT: !GetAtt AWSEBRDSDatabase.Endpoint.Port

