version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
#    environment:
#      - NODE_ENV=production
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    container_name: cvai_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cvai
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: cvai_mongo
    environment:
      - MONGO_INITDB_DATABASE=cvai
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
