name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          cd packages/server
          yarn install --frozen-lockfile

      - name: Build application
        run: |
          cd packages/server
          yarn build

      - name: Install AWS EB CLI
        run: |
          pip install awsebcli

#      - name: Generate deployment package
#        run: |
#          cd packages/server
#          zip -r deploy.zip . -x "node_modules/*" "*/node_modules/*"

      - name: Deploy to Elastic Beanstalk
        run: |
          cd packages/server
#          TODO: run bash script instead
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
